# Generated by Django 4.0.3 on 2022-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardamage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='CarId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
