# Generated by Django 4.0.3 on 2022-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardamage', '0002_remove_car_id_car_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='CarId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
