# Generated by Django 4.0.3 on 2022-03-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardamage', '0003_alter_car_carid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
