# Generated by Django 4.0.3 on 2022-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardamage', '0004_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('iscar', models.BooleanField(default=True)),
                ('isdamaged', models.BooleanField(default=True)),
                ('location', models.CharField(default='Front', max_length=16)),
                ('severity', models.CharField(default='Severe', max_length=16)),
            ],
        ),
    ]
