# Generated by Django 4.0.3 on 2022-03-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardamage', '0006_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='iscar',
        ),
        migrations.RemoveField(
            model_name='car',
            name='isdamaged',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='severity',
        ),
    ]
