# Generated by Django 4.0.3 on 2022-03-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardamage', '0007_remove_car_iscar_remove_car_isdamaged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='iscar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='isdamaged',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Front', max_length=16),
        ),
        migrations.AddField(
            model_name='car',
            name='severity',
            field=models.CharField(default='Severe', max_length=16),
        ),
    ]
